### PR TITLE
Merhawit-profile-details

### PR DESCRIPTION
**Pull request by meru20**
-Added profile image
-Added Profile Details

Closes issue#36

### CODE REVIEW

**Review by xyeras — COMMENTED** [review]
Awesome job!

**Review by xyeras — APPROVED** [review]

**Review by B-cavazos — APPROVED** [review]
looks good! 🎇

**Review by nakiacallaway — APPROVED** [review]
Great job.  Looks ready to merge.

**Review by jeffreyriosjr — APPROVED** [review]
looks good!

**Pull request merged**
